  name: 3D-Contrib

  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      name: generate-github-profile-3d-contrib
      steps:
        - uses: actions/checkout@v3
        - uses: yoshi389111/github-profile-3d-contrib@0.7.1
          env:
            GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
        - name: Commit & Push
          run: |
            git config user.name hsejsx
            git config user.email hsejsx@gmail.com
            git add -A .
            git commit -m "generated"
            git push
